name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.1
    - name: Install Packages
      run: cd ./frontend && yarn
    - name: Build page
      run: cd ./frontend && yarn build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCFteJSt8qfrE7tlWiT0qVb+USyt9e1xsCnTmG7790bfAtnPq8ycVg4eZn+fwZi+780b1eqghtCAHEfG/+LnQmkCiC0QU9tmfrRm9uoAUz/wX1kP3xGXzxfdFy1CzV9TLPAg2hf2urklXdj3QTKgwVKNWGPgZV2v6TOvWPO/YECZuaEssxJXUO5QhU2Exr6IFEdqu++Lwr4KuoXnusDMZD/rdz8PwA+jVNUVNfOsWuJ4gJZeO8oaYk/wNFS+8zld169nxrTboqPQQq71xcuubbfxDtu+A3KbbL7THxBl0JJDQxioT9zFM9Nf/g7POpP8jx8ywrUK9RDop4kP5S946hWk17vKUjQ8tsc+jTByRNvAG+3Ee38eF93XwFhseGLsPCjREU/xSWVFtIrnaMs9Q4kmGV1BkxjmA4ZoS2EPuSGPOorF+Y4nSyu1GadSVVXUM08MG4KF22csF+mLJ4MyvQfUthquLfPyivJk1W/tYEZfnyTlYyYx3v8hjBAG1rWslUH00pvUQLg9bKTAf4Pr1dkQSV7wrRLHrzW6jb8gHg9IJiqKBSJzCHEz7DumDq2t/Sc5Dgsg0cVaBOVkiwjKhFdKqLBbjKofHjvavojD7bDZtEB+3svdQSYFq0UnybWLJq3s4xvHhucmOsvOo1iyXdqQ2fXYQssrc6a3vLXahiexQ=='
        heroku_api_key: "f9b6c73b-005b-49a4-a0f6-0e63f4f17045"
        heroku_app_name: "dogegf-frontend"
        heroku_email: "gsantini@dogegf.com"
        publish_dir: ./frontend/build
