name: dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "f9b6c73b-005b-49a4-a0f6-0e63f4f17045"
          heroku_app_name: "dogegf-frontend"
          heroku_email: "gsantini@dogegf.com"
          command: "cd frontend && yarn start"
